/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as IndentsRouteImport } from './routes/indents'
import { Route as AgenticRouteImport } from './routes/agentic'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanesLaneIdRouteImport } from './routes/lanes.$laneId'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndentsRoute = IndentsRouteImport.update({
  id: '/indents',
  path: '/indents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticRoute = AgenticRouteImport.update({
  id: '/agentic',
  path: '/agentic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesLaneIdRoute = LanesLaneIdRouteImport.update({
  id: '/lanes/$laneId',
  path: '/lanes/$laneId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agentic': typeof AgenticRoute
  '/indents': typeof IndentsRoute
  '/shipments': typeof ShipmentsRoute
  '/stock': typeof StockRoute
  '/lanes/$laneId': typeof LanesLaneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agentic': typeof AgenticRoute
  '/indents': typeof IndentsRoute
  '/shipments': typeof ShipmentsRoute
  '/stock': typeof StockRoute
  '/lanes/$laneId': typeof LanesLaneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agentic': typeof AgenticRoute
  '/indents': typeof IndentsRoute
  '/shipments': typeof ShipmentsRoute
  '/stock': typeof StockRoute
  '/lanes/$laneId': typeof LanesLaneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agentic'
    | '/indents'
    | '/shipments'
    | '/stock'
    | '/lanes/$laneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agentic'
    | '/indents'
    | '/shipments'
    | '/stock'
    | '/lanes/$laneId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agentic'
    | '/indents'
    | '/shipments'
    | '/stock'
    | '/lanes/$laneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgenticRoute: typeof AgenticRoute
  IndentsRoute: typeof IndentsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  StockRoute: typeof StockRoute
  LanesLaneIdRoute: typeof LanesLaneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indents': {
      id: '/indents'
      path: '/indents'
      fullPath: '/indents'
      preLoaderRoute: typeof IndentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic': {
      id: '/agentic'
      path: '/agentic'
      fullPath: '/agentic'
      preLoaderRoute: typeof AgenticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/$laneId': {
      id: '/lanes/$laneId'
      path: '/lanes/$laneId'
      fullPath: '/lanes/$laneId'
      preLoaderRoute: typeof LanesLaneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgenticRoute: AgenticRoute,
  IndentsRoute: IndentsRoute,
  ShipmentsRoute: ShipmentsRoute,
  StockRoute: StockRoute,
  LanesLaneIdRoute: LanesLaneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
